# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mnurkass <mnurkass@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/09 08:51:48 by mnurkass          #+#    #+#              #
#    Updated: 2019/04/15 10:01:51 by mnurkass         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@gcc -o bsq -Wall -Wextra -Werror main.c distr.c lib/*.c -g  
clean:
	@/bin/rm -rf bsq bsq.dSYM 
fclean: clean
	@/bin/rm -rf bsq

re: fclean all 


   	

